---
- name: Define all the Ingress
  hosts: localhost
  pre_tasks:
    - include_tasks: tasks/dns-domain.yml
  tasks:
    - name: Create Issuer
      community.kubernetes.k8s:
        state: "{{ k8s_state }}"
        namespace: "{{ release_namespace }}"
        definition:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: ca-issuer
          spec:
            ca:
              secretName: ca-key-pair
    - name: Create Keycloak Ingress
      community.kubernetes.k8s:
        state: "{{ k8s_state }}"
        namespace: "{{ release_namespace }}"
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            annotations:
              cert-manager.io/issuer: ca-issuer
            name: keycloak-ingress
          spec:
            tls:
              - hosts:
                  - "keycloak.{{ http_app_routing_domain }}"
                secretName: keycloak-tls-secret
            rules:
              - host: "keycloak.{{ http_app_routing_domain }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: keycloak-http
                          port:
                            number: 80
