- name: Setup Helm Binary
  hosts: localhost
  become: yes
  roles:
    - role: geerlingguy.helm
- name: Setup Helm Repos
  hosts: localhost
  tasks:
    - name: Add stable chart repo
      community.kubernetes.helm_repository:
        name: stable
        repo_url: "https://kubernetes-charts.storage.googleapis.com"
    - name: Add zookeeper chart repo
      community.kubernetes.helm_repository:
        name: pravega
        repo_url: "https://charts.pravega.io"
    - name: Add solr chart repo
      community.kubernetes.helm_repository:
        name: solr-operator
        repo_url: "https://bloomberg.github.io/solr-operator/charts"
    - name: Add cert manager chart repo
      community.kubernetes.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"
    - name: Add keycloak chart repo
      community.kubernetes.helm_repository:
        name: codecentric
        repo_url: "https://codecentric.github.io/helm-charts"
