---
- name: Setup Certificate Infrastructure
  hosts: localhost
  become: yes
  pre_tasks:
    - name: make some directories
      file:
        state: directory
        path: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/private"
        - "{{ playbook_dir }}/certs"
        - "{{ playbook_dir }}/anchors"
  roles:
    - role: pacifica.ansible_certinfra
- name: Load Certs and Keys
  hosts: localhost
  vars:
    tls_crt: certs/pacifica_intermediate.io.crt
    tls_key: private/pacifica_intermediate.io.pem
  tasks:
    - name: Setup Cert Manager
      community.kubernetes.helm:
        name: cert-manager
        update_repo_cache: yes
        chart_ref: jetstack/cert-manager
        chart_version: "{{ cert_manager_version }}"
        release_namespace: "{{ release_namespace }}"
        values:
          installCRDs: true
    - name: Create Intermediate Secret
      community.kubernetes.k8s:
        state: "{{ k8s_state }}"
        namespace: "{{ release_namespace }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: ca-key-pair
          data:
            tls.crt: "{{ lookup('file', tls_crt) | b64encode }}"
            tls.key: "{{ lookup('file', tls_key) | b64encode }}"
    - name: Create Issuer
      community.kubernetes.k8s:
        state: "{{ k8s_state }}"
        namespace: "{{ release_namespace }}"
        definition:
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: ca-issuer
          spec:
            ca:
              secretName: ca-key-pair
