- name: Setup Solr Operator
  hosts: localhost
  tasks:
    - name: Deploy Solr Operator
      community.kubernetes.helm:
        name: solr-operator
        update_repo_cache: yes
        chart_ref: solr-operator/solr-operator
        release_namespace: "{{ release_namespace }}"
        values:
          image:
            tag: "{{ solr_operator_version }}"
