k8s_state: present
release_namespace: default
cert_manager_version: "v1.1.0"
nginx_ingress_version: "v0.41.2"
mariadb_operator_version: "0.0.3"
zookeeper_operator_version: "0.2.9"
solr_operator_version: "v0.2.6"

keycloak_fqdn: keycloak
keycloak_auth_username: admin
keycloak_auth_password: admin
keycloak_auth_realm: master
keycloak_client_id: gitlab
keycloak_description: Client to configure with GitLab services.

ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
aks_client_id: 72e8d42f-8b42-41b3-bf00-840ba196e8e6
aks_client_secret: '8.POeq5C-5q_g~mU_ru3W0HgEZ44eIFKgP'
azure_resource_group: "{{ ansible_user_id }}resources"
azure_username: "{{ ansible_user_id }}"
azure_location: westus
azure_cli_cmd: "{{ lookup('env', 'WORKON_HOME') | default('~/.virtualenvs') }}/azure-cli/bin/az"
azure_aks_version: 1.19.3
azure_aks_name: DataHub
azure_aks_count: 5
azure_aks_size: Standard_D4s_v3
